# Generated by Django 3.0.8 on 2020-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_backend', '0003_auto_20200808_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fs_password',
            field=models.CharField(default='helloworld', max_length=26),
            preserve_default=False,
        ),
    ]
