# Generated by Django 3.0.8 on 2020-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_backend', '0005_auto_20200809_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
