# Generated by Django 3.0.8 on 2020-08-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_backend', '0006_likes_isliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='isLiked',
        ),
    ]
